parameters:
  name: ''
  vmImage: ''
  matrix: []
  dependsOn: []

jobs:
- job: ${{ parameters.name }}
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    TEST_DIR: '$(Agent.WorkFolder)/tmp_folder'
    VIRTUALENV: 'testvenv'
    JUNITXML: 'test-data.xml'
    PYTEST_VERSION: '5.2.1'
    OMP_NUM_THREADS: '4'
    OPENBLAS_NUM_THREADS: '4'
    SKLEARN_SKIP_NETWORK_TESTS: '1'
    CCACHE_DIR: $(Pipeline.Workspace)/ccache
  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:
    - bash: |
        sudo apt-get install ccache -y
        echo "##vso[task.prependpath]/usr/lib/ccache"
      displayName: Install ccache and update PATH to use linked versions of gcc, cc, etc
      condition: eq(variables['Agent.OS'], 'Linux')
    - task: CacheBeta@0
      inputs:
        key: ccache | $(Agent.OS)
        restoreKeys: ccache
        path: $(CCACHE_DIR)
      displayName: ccache
      condition: eq(variables['Agent.OS'], 'Linux')
    - bash: echo "##vso[task.prependpath]$CONDA/bin"
      displayName: Add conda to PATH
      condition: startsWith(variables['DISTRIB'], 'conda')
    - bash: sudo chown -R $USER $CONDA
      displayName: Take ownership of conda installation
      condition: startsWith(variables['DISTRIB'], 'conda')
    - script: |
        build_tools/azure/install.sh
      displayName: 'Install'
    - script: |
        build_tools/azure/test_script.sh
      displayName: 'Test Library'
    - script: |
        build_tools/azure/test_docs.sh
      displayName: 'Test Docs'
    - script: |
        build_tools/azure/test_pytest_soft_dependency.sh
      displayName: 'Test Soft Dependency'
      condition: and(eq(variables['CHECK_PYTEST_SOFT_DEPENDENCY'], 'true'), eq(variables['DISTRIB'], 'conda'))
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '$(TEST_DIR)/$(JUNITXML)'
        testRunTitle: ${{ format('{0}-$(Agent.JobName)', parameters.name) }}
      displayName: 'Publish Test Results'
      condition: succeededOrFailed()
    - script: |
        build_tools/azure/upload_codecov.sh
      condition: and(succeeded(), eq(variables['COVERAGE'], 'true'), eq(variables['DISTRIB'], 'conda'))
      displayName: 'Upload To Codecov'
      env:
        CODECOV_TOKEN: $(CODECOV_TOKEN)
