name: "Pull Request Labeler"
on:
  schedule:
    - cron: '*/l0 * * * *'

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: thomasjpfan/labeler@v2.3.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        max-labels: "3"
