name: "Pull Request Labeler"
on:
- pull_request

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: thomasjpfan/labeler@v2.2.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        max-labels: '3'
