name: Sync Pull Request
on:
  pull_request_target:
    - types: [labeled]

jobs:
  sync_pull_request:
    if: contains(github.event.issue.labels.*.name, 'sync')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - runs: |
          git branch
