name: Sync Pull Request
on:
  pull_request_target:
    types: [labeled]

jobs:
  sync_pull_request:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'sync')
    steps:
      - uses: actions/checkout@v2
      - run: |
          git branch
